# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Knit < Formula
  desc "Knit your project context together, once."
  homepage "https://github.com/knit-dev/knit"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kerman-Sanjuan/knit/releases/download/v1.0.3/knit_darwin_amd64.tar.gz"
      sha256 "48e69b7e096f557d9bb0f2b292c7d9134d5ef6e2df94578681f52540a1cf57cd"

      define_method(:install) do
        bin.install "knit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kerman-Sanjuan/knit/releases/download/v1.0.3/knit_darwin_arm64.tar.gz"
      sha256 "4d57a78f464eb5c56178e430ef6de9377f41376cbec4c869897443ba7a31cf48"

      define_method(:install) do
        bin.install "knit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kerman-Sanjuan/knit/releases/download/v1.0.3/knit_linux_amd64.tar.gz"
      sha256 "5e1149be0ca68c63463fa61c9391b24ed513c82eb8fbe2aa9dfa8cfe335ff737"
      define_method(:install) do
        bin.install "knit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kerman-Sanjuan/knit/releases/download/v1.0.3/knit_linux_arm64.tar.gz"
      sha256 "45b467835e0638ab2de34b18da781c1b42eaac682a85c7af396e8fa772599b5e"
      define_method(:install) do
        bin.install "knit"
      end
    end
  end

  test do
    system "#{bin}/knit", "--version"
  end
end
