# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Knit < Formula
  desc "Knit your project context together, once."
  homepage "https://github.com/knit-dev/knit"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kerman-Sanjuan/knit/releases/download/v1.0.2/knit_darwin_amd64.tar.gz"
      sha256 "14c20a5bb8f7f50370b6c575a993d6a22e448458b62c5bdfcf86d1b71ea837b1"

      define_method(:install) do
        bin.install "knit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kerman-Sanjuan/knit/releases/download/v1.0.2/knit_darwin_arm64.tar.gz"
      sha256 "7dbef3717479143771221e18ea7e8b0457fbdea38de498e340a1d5edcbf7ea23"

      define_method(:install) do
        bin.install "knit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kerman-Sanjuan/knit/releases/download/v1.0.2/knit_linux_amd64.tar.gz"
      sha256 "d6e98897369e09285c75bdb880deef30b589e6b7af0a36410f0530b5931e5065"
      define_method(:install) do
        bin.install "knit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kerman-Sanjuan/knit/releases/download/v1.0.2/knit_linux_arm64.tar.gz"
      sha256 "a0b219d3a4c8740e09ffb6621d2a64b239ac2dac858bb70b9789c6b947e2357f"
      define_method(:install) do
        bin.install "knit"
      end
    end
  end

  test do
    system "#{bin}/knit", "--version"
  end
end
